import { 
  LayoutDashboard, 
  Files, 
  Building2, 
  GraduationCap, 
  BadgeCheck, 
  MapPin, 
  Settings, 
  LogOut,
  Search,
  Bell,
  HelpCircle,
  UserCircle,
  PlusCircle,
  ArrowRight,
  TrendingUp,
  Clock,
  AlertCircle,
  FileText,
  ChevronRight,
  Download,
  Filter,
  MoreVertical,
  ArrowLeft,
  Save,
  X,
  History,
  ShieldCheck,
  Info,
  ExternalLink,
  Plus
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Expedientes: Files,
  Organismos: Building2,
  Building2: Building2,
  Titulaciones: GraduationCap,
  Titulares: BadgeCheck,
  Ciudades: MapPin,
  Settings: Settings,
  LogOut: LogOut,
  Search: Search,
  Bell: Bell,
  Help: HelpCircle,
  User: UserCircle,
  PlusCircle: PlusCircle,
  ArrowRight: ArrowRight,
  TrendingUp: TrendingUp,
  Clock: Clock,
  Alert: AlertCircle,
  FileText: FileText,
  ChevronRight: ChevronRight,
  Download: Download,
  Filter: Filter,
  More: MoreVertical,
  ArrowLeft: ArrowLeft,
  Save: Save,
  X: X,
  History: History,
  Shield: ShieldCheck,
  Info: Info,
  ExternalLink: ExternalLink,
  Plus: Plus
};
